version: '1.0'
services:
  backend:
    image: ridhikajoshi/videotweets
    ports:
      - "4321:4321"
    env_file: ".env"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

      